services:
    app:
        build: '.docker'
        image: 'luismeirelles/laravel-arch-tests:latest'
        working_dir: '/app'
        volumes:
            - '.:/app'
            - '~/.config/psysh:/.config/psysh'
        network_mode: 'host'
